export enum OrderStatus {
  WAITING_FOR_PROCESSING = 'WAITING_FOR_PROCESSING',
  PROCESSING = 'PROCESSING',
  COLLECTING = 'COLLECTING',
  READY = 'READY',
  CANCELED = 'CANCELED',
  COMPLETED = 'COMPLETED'
}
